INSERT INTO player_game_stats (
    player_id, game_id, team_id, did_not_play, is_starter,
    minutes_played, seconds_played, points,
    field_goals_made, field_goals_attempted,
    three_pointers_made, three_pointers_attempted,
    free_throws_made, free_throws_attempted,
    offensive_rebounds, defensive_rebounds, total_rebounds,
    assists, steals, blocks, turnovers, personal_fouls, plus_minus,
    created_at, updated_at
) VALUES (
    @PlayerId, @GameId, @TeamId, @DidNotPlay, @IsStarter,
    @MinutesPlayed, @SecondsPlayed, @Points,
    @FieldGoalsMade, @FieldGoalsAttempted,
    @ThreePointersMade, @ThreePointersAttempted,
    @FreeThrowsMade, @FreeThrowsAttempted,
    @OffensiveRebounds, @DefensiveRebounds, @TotalRebounds,
    @Assists, @Steals, @Blocks, @Turnovers, @PersonalFouls, @PlusMinus,
    NOW(), NOW()
) ON DUPLICATE KEY UPDATE
    did_not_play = VALUES(did_not_play),
    is_starter = VALUES(is_starter),
    minutes_played = VALUES(minutes_played),
    seconds_played = VALUES(seconds_played),
    points = VALUES(points),
    field_goals_made = VALUES(field_goals_made),
    field_goals_attempted = VALUES(field_goals_attempted),
    three_pointers_made = VALUES(three_pointers_made),
    three_pointers_attempted = VALUES(three_pointers_attempted),
    free_throws_made = VALUES(free_throws_made),
    free_throws_attempted = VALUES(free_throws_attempted),
    offensive_rebounds = VALUES(offensive_rebounds),
    defensive_rebounds = VALUES(defensive_rebounds),
    total_rebounds = VALUES(total_rebounds),
    assists = VALUES(assists),
    steals = VALUES(steals),
    blocks = VALUES(blocks),
    turnovers = VALUES(turnovers),
    personal_fouls = VALUES(personal_fouls),
    plus_minus = VALUES(plus_minus),
    updated_at = NOW();