INSERT INTO player_career_stats (
    player_id, total_seasons, total_games, total_games_started,
    minutes_played, points, total_rebounds, assists,
    steals, blocks, turnovers,
    field_goals_made, field_goals_attempted,
    three_pointers_made, three_pointers_attempted,
    free_throws_made, free_throws_attempted,
    career_ppg, career_rpg, career_apg,
    career_fg_percentage, career_3pt_percentage, career_ft_percentage,
    highest_points_game, highest_rebounds_game, highest_assists_game,
    last_game_date, created_at, updated_at
) VALUES (
    @PlayerId, @TotalSeasons, @TotalGames, @TotalGamesStarted,
    @TotalMinutes, @TotalPoints, @TotalRebounds, @TotalAssists,
    @TotalSteals, @TotalBlocks, @TotalTurnovers,
    @TotalFieldGoalsMade, @TotalFieldGoalsAttempted,
    @TotalThreePointersMade, @TotalThreePointersAttempted,
    @TotalFreeThrowsMade, @TotalFreeThrowsAttempted,
    @CareerPPG, @CareerRPG, @CareerAPG,
    @CareerFGPercentage, @Career3PTPercentage, @CareerFTPercentage,
    @HighestPointsGame, @HighestReboundsGame, @HighestAssistsGame,
    @LastGameDate, NOW(), NOW()
) ON DUPLICATE KEY UPDATE
    total_seasons = VALUES(total_seasons),
    total_games = VALUES(total_games),
    total_games_started = VALUES(total_games_started),
    minutes_played = VALUES(minutes_played),
    points = VALUES(points),
    total_rebounds = VALUES(total_rebounds),
    assists = VALUES(assists),
    steals = VALUES(steals),
    blocks = VALUES(blocks),
    turnovers = VALUES(turnovers),
    field_goals_made = VALUES(field_goals_made),
    field_goals_attempted = VALUES(field_goals_attempted),
    three_pointers_made = VALUES(three_pointers_made),
    three_pointers_attempted = VALUES(three_pointers_attempted),
    free_throws_made = VALUES(free_throws_made),
    free_throws_attempted = VALUES(free_throws_attempted),
    career_ppg = VALUES(career_ppg),
    career_rpg = VALUES(career_rpg),
    career_apg = VALUES(career_apg),
    career_fg_percentage = VALUES(career_fg_percentage),
    career_3pt_percentage = VALUES(career_3pt_percentage),
    career_ft_percentage = VALUES(career_ft_percentage),
    highest_points_game = VALUES(highest_points_game),
    highest_rebounds_game = VALUES(highest_rebounds_game),
    highest_assists_game = VALUES(highest_assists_game),
    last_game_date = VALUES(last_game_date),
    updated_at = NOW();
SELECT 1;