INSERT INTO player_season_stats (
    player_id, season, season_type_id, team_id, games_played, games_started,
    minutes_played, points, field_goals_made, field_goals_attempted,
    three_pointers_made, three_pointers_attempted,
    free_throws_made, free_throws_attempted,
    offensive_rebounds, defensive_rebounds, total_rebounds,
    assists, steals, blocks, turnovers, personal_fouls,
    avg_points, avg_rebounds, avg_assists, avg_minutes,
    field_goal_percentage, three_point_percentage, free_throw_percentage,
    created_at, updated_at
) VALUES (
    @PlayerId, @Season, @SeasonTypeId, @TeamId, @GamesPlayed, @GamesStarted,
    @MinutesPlayed, @Points, @FieldGoalsMade, @FieldGoalsAttempted,
    @ThreePointersMade, @ThreePointersAttempted,
    @FreeThrowsMade, @FreeThrowsAttempted,
    @OffensiveRebounds, @DefensiveRebounds, @TotalRebounds,
    @Assists, @Steals, @Blocks, @Turnovers, @PersonalFouls,
    @AvgPoints, @AvgRebounds, @AvgAssists, @AvgMinutes,
    @FieldGoalPercentage, @ThreePointPercentage, @FreeThrowPercentage,
    NOW(), NOW()
) ON DUPLICATE KEY UPDATE
    team_id = VALUES(team_id),
    games_played = VALUES(games_played),
    games_started = VALUES(games_started),
    minutes_played = VALUES(minutes_played),
    points = VALUES(points),
    field_goals_made = VALUES(field_goals_made),
    field_goals_attempted = VALUES(field_goals_attempted),
    three_pointers_made = VALUES(three_pointers_made),
    three_pointers_attempted = VALUES(three_pointers_attempted),
    free_throws_made = VALUES(free_throws_made),
    free_throws_attempted = VALUES(free_throws_attempted),
    offensive_rebounds = VALUES(offensive_rebounds),
    defensive_rebounds = VALUES(defensive_rebounds),
    total_rebounds = VALUES(total_rebounds),
    assists = VALUES(assists),
    steals = VALUES(steals),
    blocks = VALUES(blocks),
    turnovers = VALUES(turnovers),
    personal_fouls = VALUES(personal_fouls),
    avg_points = VALUES(avg_points),
    avg_rebounds = VALUES(avg_rebounds),
    avg_assists = VALUES(avg_assists),
    avg_minutes = VALUES(avg_minutes),
    field_goal_percentage = VALUES(field_goal_percentage),
    three_point_percentage = VALUES(three_point_percentage),
    free_throw_percentage = VALUES(free_throw_percentage),
    updated_at = NOW();
SELECT id FROM player_season_stats WHERE player_id = @PlayerId AND season = @Season AND season_type_id = @SeasonTypeId AND (team_id = @TeamId OR (@TeamId IS NULL AND team_id IS NULL));