INSERT INTO player_career_stats (
    player_id, total_seasons, total_games, total_games_started,
    total_minutes, total_points, total_rebounds, total_assists,
    total_steals, total_blocks, total_turnovers,
    total_field_goals_made, total_field_goals_attempted,
    total_three_pointers_made, total_three_pointers_attempted,
    total_free_throws_made, total_free_throws_attempted,
    career_ppg, career_rpg, career_apg,
    career_fg_percentage, career_3pt_percentage, career_ft_percentage,
    highest_points_game, highest_rebounds_game, highest_assists_game,
    last_game_date, created_at, updated_at
) VALUES (
    @PlayerId, @TotalSeasons, @TotalGames, @TotalGamesStarted,
    @TotalMinutes, @TotalPoints, @TotalRebounds, @TotalAssists,
    @TotalSteals, @TotalBlocks, @TotalTurnovers,
    @TotalFieldGoalsMade, @TotalFieldGoalsAttempted,
    @TotalThreePointersMade, @TotalThreePointersAttempted,
    @TotalFreeThrowsMade, @TotalFreeThrowsAttempted,
    @CareerPPG, @CareerRPG, @CareerAPG,
    @CareerFGPercentage, @Career3PTPercentage, @CareerFTPercentage,
    @HighestPointsGame, @HighestReboundsGame, @HighestAssistsGame,
    @LastGameDate, NOW(), NOW()
) ON DUPLICATE KEY UPDATE
    total_seasons = VALUES(total_seasons),
    total_games = VALUES(total_games),
    total_games_started = VALUES(total_games_started),
    total_minutes = VALUES(total_minutes),
    total_points = VALUES(total_points),
    total_rebounds = VALUES(total_rebounds),
    total_assists = VALUES(total_assists),
    total_steals = VALUES(total_steals),
    total_blocks = VALUES(total_blocks),
    total_turnovers = VALUES(total_turnovers),
    total_field_goals_made = VALUES(total_field_goals_made),
    total_field_goals_attempted = VALUES(total_field_goals_attempted),
    total_three_pointers_made = VALUES(total_three_pointers_made),
    total_three_pointers_attempted = VALUES(total_three_pointers_attempted),
    total_free_throws_made = VALUES(total_free_throws_made),
    total_free_throws_attempted = VALUES(total_free_throws_attempted),
    career_ppg = VALUES(career_ppg),
    career_rpg = VALUES(career_rpg),
    career_apg = VALUES(career_apg),
    career_fg_percentage = VALUES(career_fg_percentage),
    career_3pt_percentage = VALUES(career_3pt_percentage),
    career_ft_percentage = VALUES(career_ft_percentage),
    highest_points_game = VALUES(highest_points_game),
    highest_rebounds_game = VALUES(highest_rebounds_game),
    highest_assists_game = VALUES(highest_assists_game),
    last_game_date = VALUES(last_game_date),
    updated_at = NOW();
SELECT 1;